fix: add missing @types/glob in runtime examples
Without this the example was failing with `src/loadSchema.ts:2:26 - error TS7016: Could not find a
declaration file for module 'glob'`